#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Jan 19, 2020 09:08:39 PM CET  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top37 {base} {
    global vTcl
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 533x465+387+132
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1170
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel 1"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    button $top.but38 \
        -activeforeground black -background $vTcl(actual_gui_bg) \
        -command input_btn_handler -disabledforeground #b8a786 \
        -font {-family {DejaVu Sans} -size 12} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Select input directory} 
    vTcl:DefineAlias "$top.but38" "InputDirBtn" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but38 <Button-2> {
        lambda e: button_handler2(e,2)
    }
    bind $top.but38 <Button-3> {
        lambda e: button_handler2(e,3)
    }
    button $top.but37 \
        -activeforeground black -background $vTcl(actual_gui_bg) \
        -command quit -disabledforeground #b8a786 \
        -font {-family {DejaVu Sans} -size 12} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Quit 
    vTcl:DefineAlias "$top.but37" "QuitButton" vTcl:WidgetProc "Toplevel1" 1
    button $top.but43 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command output_btn_handler \
        -disabledforeground #b8a786 -font {-family {DejaVu Sans} -size 12} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Select output directory} 
    vTcl:DefineAlias "$top.but43" "OutputDirBtn" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but43 <Button-2> {
        lambda e: button_handler2(e,2)
    }
    bind $top.but43 <Button-3> {
        lambda e: button_handler2(e,3)
    }
    listbox $top.lis44 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -height 200 -width 510 
    .top37.lis44 configure -font "TkFixedFont"
    .top37.lis44 insert end text
    vTcl:DefineAlias "$top.lis44" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent45 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -insertbackground black -state readonly 
    vTcl:DefineAlias "$top.ent45" "InputDirEntry" vTcl:WidgetProc "Toplevel1" 1
    button $top.but47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command export_btn_handler \
        -disabledforeground #b8a786 -font {-family {DejaVu Sans} -size 12} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Export selected to gpx} 
    vTcl:DefineAlias "$top.but47" "ExportBtn" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but47 <Button-2> {
        lambda e: button_handler2(e,2)
    }
    bind $top.but47 <Button-3> {
        lambda e: button_handler2(e,3)
    }
    label $top.lab48 \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 12 -underline 1} \
        -foreground $vTcl(actual_gui_fg) -text {1. Directories} 
    vTcl:DefineAlias "$top.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent50 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -state readonly 
    vTcl:DefineAlias "$top.ent50" "OutputDirEntry" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 12 -underline 1} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {2. Records} 
    vTcl:DefineAlias "$top.lab51" "Label1_6" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe52
    vTcl:DefineAlias "$top.tSe52" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe53
    vTcl:DefineAlias "$top.tSe53" "TSeparator1_7" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab54 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {Powered by Out of Pluto} 
    vTcl:DefineAlias "$top.lab54" "Label2" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but38 \
        -in $top -x 10 -y 40 -width 200 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but37 \
        -in $top -x 460 -y 390 -anchor nw -bordermode ignore 
    place $top.but43 \
        -in $top -x 10 -y 90 -width 200 -relwidth 0 -height 33 -anchor nw \
        -bordermode ignore 
    place $top.lis44 \
        -in $top -x 10 -y 180 -width 510 -relwidth 0 -height 200 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent45 \
        -in $top -x 220 -y 50 -width 300 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 10 -y 390 -width 200 -relwidth 0 -height 33 -anchor nw \
        -bordermode ignore 
    place $top.lab48 \
        -in $top -x 10 -y 10 -anchor nw -bordermode ignore 
    place $top.ent50 \
        -in $top -x 220 -y 100 -width 300 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -y 150 -width 111 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.tSe52 \
        -in $top -x 10 -y 140 -width 510 -anchor nw -bordermode inside 
    place $top.tSe53 \
        -in $top -x 10 -y 440 -width 510 -height 2 -anchor nw \
        -bordermode ignore 
    place $top.lab54 \
        -in $top -x 10 -y 443 -width 161 -height 21 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

